# Generated by Django 6.1.1 on 2026-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_email_deleted_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, error_messages={'unique': 'Ya existe un empleado registrado con este correo.'}, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email', 'is_deleted'], name='emp_email_deleted_idx'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
